# Site settings
author: Brad McCollum
title: Code Between the Lines
header-img: img/home-bg.png
email: btmcco8@gmail.com
copyright_name: Brad McCollum
description: > # this means to ignore newlines until "baseurl:"
  A journey in pursuit of creativity, passion, proficiency, and code!
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: btmccollum
github_username:  btmccollum

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
